# Dockerfile.frontend
FROM nginx:alpine

# copy static HTML + custom nginx config
COPY templates/index.html /usr/share/nginx/html/index.html
COPY nginx.conf        /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
