apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: matrix-frontend
  template:
    metadata:
      labels:
        app: matrix-frontend
    spec:
      containers:
      - name: matrix-frontend
        image: arunchaitanya93/matrix-frontend:latest
        ports:
        - containerPort: 80
